docs: Add docs and rename plotting to chartly
ec-intl/chartly pull request #3
Opened 2024-10-17 18:03 UTC by Azendae-Popo

# 🥇 Generic Pull Request 🥇
## Elizabeth Consulting International Inc
### Purpose & Objective

***

- [x] This PR satisfies the PR checklist.

2024-10-17 21:37 UTC, cmbengue-ec-intl requested changes
Please update based on our discussion.

2024-10-21 21:49 UTC, Azendae-Popo commented
![image](https://github.com/user-attachments/assets/1a82f8d4-3b87-4b07-9818-25df77ba3c87)

2024-10-22 18:16 UTC, cmbengue-ec-intl requested changes
Minor refactoring is needed. See the comments below.

2024-10-22 18:17 UTC, Azendae-Popo commented on src/chartly/chartly.py
Alrighty

2024-10-24 13:48 UTC, cmbengue-ec-intl approved these changes
This looks good. Great work on this. 💯

2024-10-24 13:51 UTC, merged